---
apiVersion: v1
kind: Template
labels: 
  template: ${PIPELINE_NAME}-pipeline
metadata: 
  name: ${PIPELINE_NAME}-pipeline
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata: 
    name: "${PIPELINE_NAME}-pipeline"
  spec:
    source:
      git:
        uri: "${PIPELINE_REPO}"
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: ${PIPELINE_PATH}
parameters:
- name: PIPELINE_NAME
  description: Pipeline identifier
  required: true
- name: PIPELINE_REPO
  description: The repository (github) where the Jenkinsfile is located (eg. https://github.com/bcgov/EDUC-PEN-REQUEST)
  required: true
- name: PIPELINE_PATH
  description: the path within the repo where the jenkinsfile is located (eg. /tools/openshift/Jenkinsfile)
  required: true