---
apiVersion: v1
kind: Template
labels:
  template: "${REPO_NAME}-template"
metadata:
  name: "${REPO_NAME}-backend-dc"
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp:
    labels:
      app: "${APP_NAME}-${JOB_NAME}"
    name: "${APP_NAME}-backend-${JOB_NAME}"
  spec:
    replicas: 2
    selector:
      app: "${APP_NAME}-${JOB_NAME}"
      deploymentconfig: "${APP_NAME}-backend-${JOB_NAME}"
    strategy:
      resources: {}
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp:
        labels:
          app: "${APP_NAME}-${JOB_NAME}"
          deploymentconfig: "${APP_NAME}-backend-${JOB_NAME}"
      spec:
        containers:
        - image: docker-registry.default.svc:5000/${NAMESPACE}/${REPO_NAME}-backend:${JOB_NAME}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: "/api"
              port: 8081
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: "${APP_NAME}-backend-${JOB_NAME}"
          ports:
          - containerPort: 8081
            protocol: TCP
          - containerPort: 443
            protocol: TCP 
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: "/api"
              port: 8081
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          env:
          - name: SERVER_FRONTEND
            value: "https://${HOST_ROUTE}"
          - name: ISSUER
            valueFrom:
              configMapKeyRef:
                key: ISSUER
                name: pen-request-config
          - name: UI_PRIVATE_KEY
            valueFrom:
              configMapKeyRef:
                key: UI_PRIVATE_KEY
                name: pen-request-config
          - name: UI_PUBLIC_KEY
            valueFrom:
              configMapKeyRef:
                key: UI_PUBLIC_KEY
                name: pen-request-config
          - name: SOAM_PUBLIC_KEY
            valueFrom:
              configMapKeyRef:
                key: SOAM_PUBLIC_KEY
                name: pen-request-config
          - name: SOAM_DISCOVERY
            valueFrom:
              configMapKeyRef:
                key: SOAM_DISCOVERY
                name: pen-request-config
          - name: SOAM_CLIENT_ID
            valueFrom:
              configMapKeyRef:
                key: SOAM_CLIENT_ID
                name: pen-request-config
          - name: SOAM_CLIENT_SECRET
            valueFrom:
              configMapKeyRef:
                key: SOAM_CLIENT_SECRET
                name: pen-request-config
          - name: SOAM_URL
            valueFrom:
              configMapKeyRef:
                key: SOAM_URL
                name: pen-request-config
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - "${APP_NAME}-backend-${JOB_NAME}"
        from:
          kind: ImageStreamTag
          name: "${REPO_NAME}-backend:${JOB_NAME}"
          namespace: "${NAMESPACE}"
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp:
    labels:
      app: "${APP_NAME}-${JOB_NAME}"
    name: "${APP_NAME}-backend-${JOB_NAME}"
  spec:
    ports:
    - name: 8081-tcp
      port: 8081
      protocol: TCP
      targetPort: 8081
    - name: 443-https
      port: 443
      protocol: TCP 
      targetPort: 443
    selector:
      app: "${APP_NAME}-${JOB_NAME}"
      deploymentconfig: "${APP_NAME}-backend-${JOB_NAME}"
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: 'true'
    labels:
      app: "${APP_NAME}-${JOB_NAME}"
    name: "${APP_NAME}-backend-${JOB_NAME}"
  spec:
    host: "${HOST_ROUTE}"
    path: /api
    port:
      targetPort: 8081-tcp
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: "${APP_NAME}-backend-${JOB_NAME}"
      weight: 100
    wildcardPolicy: None
parameters:
- name: REPO_NAME
  description: Application repository name
  required: true
- name: JOB_NAME
  description: Job identifier (i.e. 'pr-5' OR 'master')
  required: true
- name: NAMESPACE
  description: Target namespace reference (i.e. 'k8vopl-dev')
  required: true
- name: APP_NAME
  description: Application name
  required: true
- name: HOST_ROUTE
  description: The host the route will use to expose service outside cluster 
  required: true