name: E2E Tests
on: [push]

jobs:
  build:
    name: Run Tests Across Node.js Versions and Operating Systems
    runs-on: macos-latest
    steps:
      - uses: actions/setup-node@v1
      - uses: actions/checkout@v1
      - name: Run TestCafe Tests
        uses: DevExpress/testcafe-action@latest
        with:
          args: "safari ./frontend/tests/e2e/testCases/staff-login.js"